"
A Learning Overview topic identifies the learning objectives, includes other information helpful to the learner, such as prerequisites, duration, intended audience, and can include information and strategies that seeks to gain attention and stimulate recall of prior learning. [page](https://dita-lang.org/1.3/dita/langref/learningtraining/learningoverview)

See also {{gtClass:LcPrereqs}}
"
Class {
	#name : #LearningOverview,
	#superclass : #Object,
	#category : #GtCurriculum
}
